### ISSUE TITLE
异常处理中间件

### ISSUE THREAD

**Issue by lvgithub** [atian25/node-cookbook#3]
异常处理中间件，全部异常都返回 http status 500 ？,不对于参数错误等，status=4xx ？做区分吗
https://github.com/atian25/node-cookbook/blob/10758da1b6da055ad5cfdcdfde934fda4a4df131/example/05_koa/app/middleware/error_handler.js#L9

**Comment by atian25** [comment]
简化处理，本章重点并不在这里。如果写到更完美，那直接看 egg 源码不就好了

**Comment by lvgithub** [comment]
支持天猪，在这里学到很多
